project_id = "rzkazstofvdrccvqgfvt"

[functions.binance-get-price]
verify_jwt = true

[functions.binance-execute-trade]
verify_jwt = true

[functions.binance-get-balance]
verify_jwt = true

[functions.store-api-credentials]
verify_jwt = true
